
ALTER TABLE public.metas
  ADD COLUMN IF NOT EXISTS descricao text DEFAULT '',
  ADD COLUMN IF NOT EXISTS local_obra text DEFAULT '',
  ADD COLUMN IF NOT EXISTS orcamento numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS custo_atual numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equipe text DEFAULT '',
  ADD COLUMN IF NOT EXISTS fornecedor text DEFAULT '',
  ADD COLUMN IF NOT EXISTS etapa text DEFAULT '',
  ADD COLUMN IF NOT EXISTS peso numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tags text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS data_inicio date,
  ADD COLUMN IF NOT EXISTS frequencia_checkin text DEFAULT 'semanal',
  ADD COLUMN IF NOT EXISTS risco text DEFAULT '',
  ADD COLUMN IF NOT EXISTS observacoes text DEFAULT '',
  ADD COLUMN IF NOT EXISTS aprovador text DEFAULT '',
  ADD COLUMN IF NOT EXISTS departamento text DEFAULT '',
  ADD COLUMN IF NOT EXISTS tipo_meta text DEFAULT 'quantitativa',
  ADD COLUMN IF NOT EXISTS indicador_chave text DEFAULT '',
  ADD COLUMN IF NOT EXISTS fonte_dados text DEFAULT '',
  ADD COLUMN IF NOT EXISTS impacto text DEFAULT '',
  ADD COLUMN IF NOT EXISTS dependencias text DEFAULT '',
  ADD COLUMN IF NOT EXISTS marco_critico text DEFAULT '',
  ADD COLUMN IF NOT EXISTS percentual_concluido numeric DEFAULT 0;
